
import Ajv from 'ajv';

activityPubSchemas = new Ajv();

activityPubSchemas.addSchema(require('./schemas/JSONLD.json'));
activityPubSchemas.addSchema(require('./schemas/ActivityPub.json'));

activityPubSchemas.addSchema(require("./schemas/type/Delete.json"),"Delete.json");
activityPubSchemas.addSchema(require("./schemas/type/Page.json"),"Page.json");
activityPubSchemas.addSchema(require("./schemas/type/Image.json"),"Image.json");
activityPubSchemas.addSchema(require("./schemas/type/Offer.json"),"Offer.json");
activityPubSchemas.addSchema(require("./schemas/type/Article.json"),"Article.json");
activityPubSchemas.addSchema(require("./schemas/type/Activity.json"),"Activity.json");
activityPubSchemas.addSchema(require("./schemas/type/Accept.json"),"Accept.json");
activityPubSchemas.addSchema(require("./schemas/type/Group.json"),"Group.json");
activityPubSchemas.addSchema(require("./schemas/type/Read.json"),"Read.json");
activityPubSchemas.addSchema(require("./schemas/type/TentativeReject.json"),"TentativeReject.json");
activityPubSchemas.addSchema(require("./schemas/type/Reject.json"),"Reject.json");
activityPubSchemas.addSchema(require("./schemas/type/IntransitiveActivity.json"),"IntransitiveActivity.json");
activityPubSchemas.addSchema(require("./schemas/type/Listen.json"),"Listen.json");
activityPubSchemas.addSchema(require("./schemas/type/Ignore.json"),"Ignore.json");
activityPubSchemas.addSchema(require("./schemas/type/Collection.json"),"Collection.json");
activityPubSchemas.addSchema(require("./schemas/type/Add.json"),"Add.json");
activityPubSchemas.addSchema(require("./schemas/type/Video.json"),"Video.json");
activityPubSchemas.addSchema(require("./schemas/type/TentativeAccept.json"),"TentativeAccept.json");
activityPubSchemas.addSchema(require("./schemas/type/Invite.json"),"Invite.json");
activityPubSchemas.addSchema(require("./schemas/type/Leave.json"),"Leave.json");
activityPubSchemas.addSchema(require("./schemas/type/Tombstone.json"),"Tombstone.json");
activityPubSchemas.addSchema(require("./schemas/type/Flag.json"),"Flag.json");
activityPubSchemas.addSchema(require("./schemas/type/CollectionPage.json"),"CollectionPage.json");
activityPubSchemas.addSchema(require("./schemas/type/Join.json"),"Join.json");
activityPubSchemas.addSchema(require("./schemas/type/Service.json"),"Service.json");
activityPubSchemas.addSchema(require("./schemas/type/OrderedCollectionPage.json"),"OrderedCollectionPage.json");
activityPubSchemas.addSchema(require("./schemas/type/Remove.json"),"Remove.json");
activityPubSchemas.addSchema(require("./schemas/type/Mention.json"),"Mention.json");
activityPubSchemas.addSchema(require("./schemas/type/Note.json"),"Note.json");
activityPubSchemas.addSchema(require("./schemas/type/Create.json"),"Create.json");
activityPubSchemas.addSchema(require("./schemas/type/Profile.json"),"Profile.json");
activityPubSchemas.addSchema(require("./schemas/type/Audio.json"),"Audio.json");
activityPubSchemas.addSchema(require("./schemas/type/Undo.json"),"Undo.json");
activityPubSchemas.addSchema(require("./schemas/type/Place.json"),"Place.json");
activityPubSchemas.addSchema(require("./schemas/type/Question.json"),"Question.json");
activityPubSchemas.addSchema(require("./schemas/type/Link.json"),"Link.json");
activityPubSchemas.addSchema(require("./schemas/type/Actor.json"),"Actor.json");
activityPubSchemas.addSchema(require("./schemas/type/Object.json"),"Object.json");
activityPubSchemas.addSchema(require("./schemas/type/Person.json"),"Person.json");
activityPubSchemas.addSchema(require("./schemas/type/Dislike.json"),"Dislike.json");
activityPubSchemas.addSchema(require("./schemas/type/Document.json"),"Document.json");
activityPubSchemas.addSchema(require("./schemas/type/OrderedCollection.json"),"OrderedCollection.json");
activityPubSchemas.addSchema(require("./schemas/type/Event.json"),"Event.json");
activityPubSchemas.addSchema(require("./schemas/type/Announce.json"),"Announce.json");
activityPubSchemas.addSchema(require("./schemas/type/Organization.json"),"Organization.json");
activityPubSchemas.addSchema(require("./schemas/type/Application.json"),"Application.json");
activityPubSchemas.addSchema(require("./schemas/type/Update.json"),"Update.json");
activityPubSchemas.addSchema(require("./schemas/type/Block.json"),"Block.json");
activityPubSchemas.addSchema(require("./schemas/type/Move.json"),"Move.json");
activityPubSchemas.addSchema(require("./schemas/type/View.json"),"View.json");
activityPubSchemas.addSchema(require("./schemas/type/Follow.json"),"Follow.json");
activityPubSchemas.addSchema(require("./schemas/type/Travel.json"),"Travel.json");
activityPubSchemas.addSchema(require("./schemas/type/Relationship.json"),"Relationship.json");
activityPubSchemas.addSchema(require("./schemas/type/Arrive.json"),"Arrive.json");
activityPubSchemas.addSchema(require("./schemas/type/Like.json"),"Like.json");
